# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('batch_id', models.CharField(max_length=20, blank=True, null=True)),
                ('no_of_jobs', models.IntegerField(blank=True, null=True)),
                ('mode_of_batch', models.CharField(max_length=20, blank=True, null=True)),
                ('status_of_batch', models.CharField(max_length=20, blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_batch_cost', models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=1)),
                ('total_batch_weight', models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=1)),
            ],
            options={
                'verbose_name_plural': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('commented_by', models.CharField(max_length=255, blank=True, null=True)),
                ('msg_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['-msg_created_on'],
            },
        ),
        migrations.CreateModel(
            name='ContainerTypes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('name_of_container', models.CharField(max_length=100, blank=True, null=True)),
                ('number_of_container', models.CharField(max_length=100, blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Types of Containers',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='DockReceipt',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('tracking_number', models.CharField(max_length=100, blank=True, null=True)),
                ('exporter_name_and_address', models.CharField(max_length=100, blank=True, null=True)),
                ('zip_code', models.CharField(max_length=100, blank=True, null=True)),
                ('consigned_to', models.CharField(max_length=100, blank=True, null=True)),
                ('notify_party_name_and_address', models.CharField(max_length=100, blank=True, null=True)),
                ('document_number', models.CharField(max_length=100, blank=True, null=True)),
                ('bl_or_awb_number', models.CharField(max_length=100, blank=True, null=True)),
                ('export_references', models.CharField(max_length=100, blank=True, null=True)),
                ('forwarding_agent_fmc_no', models.CharField(max_length=100, blank=True, null=True)),
                ('state_and_country_of_origin_or_ftz_number', models.CharField(max_length=100, blank=True, null=True)),
                ('domestic_routing', models.CharField(max_length=100, blank=True, null=True)),
                ('loading_pier', models.CharField(max_length=100, blank=True, null=True)),
                ('type_of_move', models.CharField(max_length=100, blank=True, null=True)),
                ('containerized', models.BooleanField(default=False)),
                ('precarriage_by', models.CharField(max_length=100, blank=True, null=True)),
                ('place_of_receipt_by_precarrier', models.CharField(max_length=100, blank=True, null=True)),
                ('exporting_carrier', models.CharField(max_length=100, blank=True, null=True)),
                ('port_of_loading', models.CharField(max_length=100, blank=True, null=True)),
                ('foreign_port_of_unloading', models.CharField(max_length=100, blank=True, null=True)),
                ('place_of_delivery_by_oncarrier', models.CharField(max_length=100, blank=True, null=True)),
                ('mks_nos', models.CharField(max_length=100, blank=True, null=True)),
                ('no_of_pkgs', models.IntegerField(blank=True, null=True)),
                ('description_of_package_and_goods', models.CharField(max_length=100, blank=True, null=True)),
                ('gross_weight', models.IntegerField(blank=True, null=True)),
                ('measurement', models.CharField(max_length=100, blank=True, null=True)),
                ('lighter_truck', models.CharField(max_length=100, blank=True, null=True)),
                ('arrived_date', models.CharField(max_length=100, blank=True, null=True)),
                ('arrived_time', models.CharField(max_length=100, blank=True, null=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(max_length=100, blank=True, null=True)),
                ('batch', models.CharField(max_length=100, blank=True, null=True)),
                ('unloaded_date', models.CharField(max_length=100, blank=True, null=True)),
                ('unloaded_time', models.CharField(max_length=100, blank=True, null=True)),
                ('checked_by', models.CharField(max_length=100, blank=True, null=True)),
                ('placed_location', models.CharField(max_length=100, blank=True, null=True)),
                ('receiving_clerk_name', models.CharField(max_length=100, blank=True, null=True)),
                ('date_from_receiving_clerk', models.CharField(max_length=100, blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('name_of_doc', models.CharField(max_length=100, blank=True, null=True)),
                ('doc_obj', models.FileField(blank=True, null=True, upload_to='item_photo')),
                ('doc_recieved', models.CharField(max_length=100, blank=True, null=True)),
                ('doc_date', models.CharField(max_length=100, blank=True, null=True)),
                ('doc_action', models.CharField(max_length=100, blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('charge_type', models.CharField(max_length=50, blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True, default=0.0)),
                ('paid_by', models.CharField(max_length=50, blank=True, null=True)),
                ('received', models.CharField(max_length=50, blank=True, null=True)),
                ('date_paid', models.CharField(max_length=50, blank=True, null=True)),
                ('refundablle_as', models.CharField(max_length=50, blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Finances',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('box_length', models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=1)),
                ('box_width', models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=1)),
                ('box_height', models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=1)),
                ('box_weight', models.DecimalField(blank=True, null=True, default=0, max_digits=15, decimal_places=1)),
                ('box_weight_K', models.DecimalField(blank=True, null=True, default=0, max_digits=15, decimal_places=1)),
                ('job_paar', models.BooleanField(default=False)),
                ('ref_number', models.CharField(max_length=50, blank=True, null=True)),
                ('company_name', models.CharField(max_length=50, blank=True, null=True)),
                ('customer_type', models.CharField(max_length=50, blank=True, null=True)),
                ('shippers_name', models.CharField(max_length=150, blank=True, null=True)),
                ('shippers_email', models.CharField(max_length=150, blank=True, null=True)),
                ('shippers_number', models.CharField(max_length=150, blank=True, null=True)),
                ('shippers_country', models.CharField(max_length=150, blank=True, null=True)),
                ('shippers_address', models.CharField(max_length=150, blank=True, null=True)),
                ('consignees_name', models.CharField(max_length=150, blank=True, null=True)),
                ('consignees_number', models.CharField(max_length=150, blank=True, null=True)),
                ('consignee_email', models.CharField(max_length=150, blank=True, null=True)),
                ('consignee_country', models.CharField(max_length=150, blank=True, null=True)),
                ('consignees_address', models.CharField(max_length=150, blank=True, null=True)),
                ('country_of_origin', models.CharField(max_length=150, blank=True, null=True)),
                ('country_of_arrival', models.CharField(max_length=150, blank=True, null=True)),
                ('port_of_destination', models.CharField(max_length=150, blank=True, null=True)),
                ('port_of_arrival', models.CharField(max_length=150, blank=True, null=True)),
                ('job_vessel_name', models.CharField(max_length=50, blank=True, null=True)),
                ('job_awl_bol_number', models.CharField(max_length=50, blank=True, null=True)),
                ('paar_date', models.DateField(blank=True, null=True)),
                ('insured', models.BooleanField(default=False)),
                ('insurance_date', models.DateField(blank=True, null=True)),
                ('packing_list', models.BooleanField(default=False)),
                ('packing_list_date', models.CharField(max_length=50, blank=True, null=True)),
                ('job_son', models.BooleanField(default=False)),
                ('son_date', models.DateField(blank=True, null=True)),
                ('job_ccro', models.BooleanField(default=False)),
                ('ccro_date', models.DateField(blank=True, null=True)),
                ('duty_exemption', models.BooleanField(default=False)),
                ('duty_exemption_date', models.DateField(blank=True, null=True)),
                ('job_start_date', models.CharField(max_length=200, blank=True, null=True)),
                ('job_end_date', models.CharField(max_length=200, blank=True, null=True)),
                ('job_date_of_arrival', models.CharField(max_length=200, blank=True, null=True)),
                ('job_status', models.CharField(max_length=50, blank=True, null=True)),
                ('job_id', models.CharField(max_length=50, blank=True, null=True)),
                ('job_type', models.CharField(max_length=20, blank=True, null=True)),
                ('job_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_in_transit', models.BooleanField(default=False)),
                ('job_arrived', models.BooleanField(default=False)),
                ('job_undergoing_clearnace', models.BooleanField(default=False)),
                ('job_undergoing_ammendment', models.BooleanField(default=False)),
                ('job_examined', models.BooleanField(default=False)),
                ('job_cleared', models.BooleanField(default=False)),
                ('job_completed', models.BooleanField(default=False)),
                ('job_invoiced', models.BooleanField(default=False)),
                ('job_paid_for', models.BooleanField(default=False)),
                ('job_processing', models.BooleanField(default=False)),
                ('job_issue_resolution', models.BooleanField(default=False)),
                ('job_details', models.BooleanField(default=False)),
                ('job_descript', models.BooleanField(default=False)),
                ('job_documentation', models.BooleanField(default=False)),
                ('job_finances', models.BooleanField(default=False)),
                ('job_arr_stat', models.BooleanField(default=False)),
                ('job_paid', models.BooleanField(default=False)),
                ('job_cost', models.FloatField(blank=True, null=True, default=0.0)),
                ('job_amount_paid', models.FloatField(blank=True, null=True, default=1.0)),
                ('job_amount_balance', models.FloatField(blank=True, null=True, default=1.0)),
                ('vat', models.BooleanField(default=False)),
                ('demurrage', models.BooleanField(default=False)),
                ('job_new_comment', models.BooleanField(default=False)),
                ('job_commented_on', models.BooleanField(default=False)),
                ('demurrage_grace_period', models.IntegerField(blank=True, null=True, default=7)),
                ('demurrage_start_date', models.DateField(blank=True, null=True)),
                ('demurrage_end_date', models.DateField(blank=True, null=True)),
                ('number_of_pieces_to_ship', models.IntegerField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(blank=True, null=True, default=0.0, max_digits=15, decimal_places=1)),
                ('box_weight_Actual', models.DecimalField(blank=True, null=True, default=0.0, max_digits=15, decimal_places=1)),
                ('nature_of_goods', models.CharField(max_length=200, blank=True, null=True)),
                ('quantity_of_goods', models.CharField(max_length=200, blank=True, null=True)),
                ('airline_tracking_number', models.CharField(max_length=100, blank=True, null=True)),
                ('place_of_execution', models.CharField(max_length=100, blank=True, null=True)),
                ('no_of_arrival_batches', models.IntegerField(blank=True, null=True, default=0)),
                ('handling_info', models.TextField(max_length=100, blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_comment', models.TextField(blank=True, null=True)),
                ('note_on_the_package', models.TextField(max_length=200, blank=True, null=True)),
                ('job_route', models.CharField(max_length=100, blank=True, null=True)),
                ('job_arrival_status', models.BooleanField(default=False)),
                ('job_financial_info', models.BooleanField(default=False)),
                ('job_arrival_status_mode', models.CharField(max_length=100, blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('batch_type', models.ForeignKey(blank=True, null=True, to='zodiakApp.Batch')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'ordering': ['-job_created_on'],
            },
        ),
        migrations.CreateModel(
            name='JobModes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('name', models.CharField(max_length=20, blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Job Modes',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='MiniBatches',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('no_of_packages', models.IntegerField(blank=True, null=True)),
                ('job_description', models.CharField(max_length=255, blank=True, null=True)),
                ('carrier_name', models.CharField(max_length=50, blank=True, null=True)),
                ('mini_batch_id', models.CharField(max_length=50, blank=True, null=True)),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('gross_wgh', models.FloatField(blank=True, null=True, default=0.0)),
                ('net_wgh', models.FloatField(blank=True, null=True, default=0.0)),
                ('exp_date_of_arrival', models.DateField(blank=True, null=True)),
                ('date_of_arrival', models.DateField(blank=True, null=True)),
                ('batch_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, to='zodiakApp.Job')),
            ],
            options={
                'verbose_name_plural': 'Mini Batches',
                'ordering': ['-batch_created_on'],
            },
        ),
        migrations.CreateModel(
            name='OfficeUseOnly',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('internal_evaluation', models.TextField(blank=True, null=True)),
                ('mode_of_operation', models.CharField(max_length=20, blank=True, null=True)),
                ('special_request', models.CharField(max_length=20, blank=True, null=True)),
                ('staff_evaluation', models.TextField(blank=True, null=True)),
                ('off_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Office Use only',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PrimaryContact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('contact_name', models.CharField(max_length=50, blank=True, null=True)),
                ('contact_position', models.CharField(max_length=50, blank=True, null=True)),
                ('contact_department', models.CharField(max_length=50, blank=True, null=True)),
                ('contact_phone_number', models.CharField(max_length=50, blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=50, blank=True, null=True)),
                ('contact_address_1', models.CharField(max_length=20, blank=True, null=True)),
                ('primary_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('user_acc', models.ForeignKey(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Primary Contact',
                'ordering': ['-user_acc'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('item', models.CharField(max_length=20, blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price_per_item', models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=1)),
                ('total_cost', models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=1)),
                ('notes_on_job', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Quotation',
                'ordering': ['-user_acct'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipManager',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('rm_name', models.CharField(max_length=20, blank=True, null=True)),
                ('rm_email', models.CharField(max_length=20, blank=True, null=True)),
                ('rm_position', models.CharField(max_length=20, blank=True, null=True)),
                ('rm_alt_email', models.CharField(max_length=20, blank=True, null=True)),
                ('rm_contact_no', models.CharField(max_length=20, blank=True, null=True)),
                ('rm_designation', models.CharField(max_length=20, blank=True, null=True)),
                ('rm_office_address', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('rm_created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Relationship Managers',
                'ordering': ['-rm_created_on'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryContact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('sec_contact_name', models.CharField(max_length=50, blank=True, null=True)),
                ('sec_contact_position', models.CharField(max_length=50, blank=True, null=True)),
                ('sec_contact_department', models.CharField(max_length=50, blank=True, null=True)),
                ('sec_contact_phone_number', models.CharField(max_length=50, blank=True, null=True)),
                ('sec_contact_email', models.EmailField(max_length=50, blank=True, null=True)),
                ('sec_contact_address_1', models.CharField(max_length=20, blank=True, null=True)),
                ('sec_contact_created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('sec_user_acc', models.ForeignKey(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Secondary Contact',
                'ordering': ['-sec_user_acc'],
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('shippers_name', models.CharField(max_length=150, blank=True, null=True)),
                ('shippers_email', models.CharField(max_length=150, blank=True, null=True)),
                ('shippers_number', models.CharField(max_length=150, blank=True, null=True)),
                ('shippers_country', models.CharField(max_length=150, blank=True, null=True)),
                ('shippers_address', models.CharField(max_length=150, blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Shippers',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('name', models.CharField(max_length=100, blank=True, null=True)),
                ('alias', models.CharField(max_length=100, blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='StatusRec',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('stat_type', models.CharField(max_length=50, blank=True, null=True)),
                ('stat_date', models.CharField(max_length=50, blank=True, null=True)),
                ('stat_comment', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_stat', models.ForeignKey(blank=True, null=True, to='zodiakApp.Job')),
            ],
            options={
                'verbose_name_plural': 'StatusRec',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('profile_updated', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=50, blank=True, null=True)),
                ('type_of_business', models.TextField(blank=True, null=True)),
                ('comp_name', models.TextField(blank=True, null=True)),
                ('office_aadress', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_passport', models.ImageField(blank=True, null=True, upload_to='item_photo')),
                ('user_cac', models.ImageField(blank=True, null=True, upload_to='item_photo')),
                ('user_other_means_of_id', models.ImageField(blank=True, null=True, upload_to='item_photo')),
                ('inputter', models.BooleanField(default=True)),
                ('authorizer', models.BooleanField(default=False)),
                ('rm_updated', models.BooleanField(default=False)),
                ('reporter', models.BooleanField(default=False)),
                ('administrator', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('staff_account', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=20, blank=True, null=True)),
                ('state', models.CharField(max_length=20, blank=True, null=True)),
                ('website', models.CharField(max_length=50, blank=True, null=True)),
                ('cust_type', models.CharField(max_length=50, blank=True, null=True)),
                ('acc_owner', models.CharField(max_length=50, blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Accounts',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='relationshipmanager',
            name='rm_client',
            field=models.ForeignKey(blank=True, null=True, to='zodiakApp.UserAccount'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='user_acct',
            field=models.ForeignKey(blank=True, null=True, to='zodiakApp.UserAccount'),
        ),
        migrations.AddField(
            model_name='officeuseonly',
            name='rm_client_obj',
            field=models.ForeignKey(blank=True, null=True, to='zodiakApp.UserAccount'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_user_acc',
            field=models.ForeignKey(blank=True, null=True, to='zodiakApp.UserAccount'),
        ),
        migrations.AddField(
            model_name='finances',
            name='job_finance',
            field=models.ForeignKey(blank=True, null=True, to='zodiakApp.Job'),
        ),
        migrations.AddField(
            model_name='documents',
            name='job_obj_doc',
            field=models.ForeignKey(blank=True, null=True, to='zodiakApp.Job'),
        ),
        migrations.AddField(
            model_name='dockreceipt',
            name='shipping_package',
            field=models.ForeignKey(blank=True, null=True, to='zodiakApp.Job'),
        ),
        migrations.AddField(
            model_name='containertypes',
            name='job_obj_cont',
            field=models.ForeignKey(blank=True, null=True, to='zodiakApp.Job'),
        ),
        migrations.AddField(
            model_name='comments',
            name='job_message',
            field=models.ForeignKey(blank=True, null=True, to='zodiakApp.Job'),
        ),
    ]
