# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zodiakApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name_plural': 'DocType',
            },
        ),
        migrations.CreateModel(
            name='newPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name_plural': 'PayType',
            },
        ),
        migrations.CreateModel(
            name='newStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name_plural': 'StatType',
            },
        ),
        migrations.AlterModelOptions(
            name='finances',
            options={'ordering': ['charge_type'], 'verbose_name_plural': 'Finances'},
        ),
        migrations.RemoveField(
            model_name='shippers',
            name='removed',
        ),
        migrations.AddField(
            model_name='finances',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='item_photo'),
        ),
        migrations.AddField(
            model_name='finances',
            name='validity_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
