# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-15 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiakApp', '0086_auto_20190310_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='comp_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
