# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-12 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zodiakApp', '0087_useraccount_comp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_date', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_comment', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zodiakApp.Job')),
            ],
            options={
                'ordering': ['-created_on'],
                'verbose_name_plural': 'StatusRec',
            },
        ),
        migrations.AddField(
            model_name='documents',
            name='doc_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='doc_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='doc_recieved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finances',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finances',
            name='received',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='cust_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='date_paid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
